sudo: true
language: node_js
node_js:
- '4'
cache:
  directories:
  - node_modules
script:
- npm test
deploy:
  provider: npm
  email: josh@nline.io
  api_key:
    secure: Riml2Bbzeo0ZyipRK4CfmHvpLebypPQ40jpRsfwqpUC7tN24kS7cXjchu8OY2umScyiCgoDT5hXOdWqnUEAJPjh9Vu7kddmibfklGSqP2pjIpxq0cOzVJdrvdubCjFYA+Fac8y0+VzEo+rbfY5u2USDuhgZHNIsffmyR4Zb4W+IQHizdddMz7z+FvZr4VCoOoJqlYCtMqweGsPv8qhizCNDpk3xOqFptPMbzf4SQ0RhB6skWWjJxM83ZM9TFDYsSfMaIlyiDK3HAQ+keDm8RC1Ac4TwuHdnyLNorNsoc64UqbOtHpOH9/ZJsb9OlUzrYIHrgFlCHPlJ5Za2NcLJG5fWLaKNXOZ5EImELFf2loUVAZB5p1adhxN5DOXaXiG788xWPuJDUaO1t52+XdUdWwK+t6RVNCX9wfHjQd3Z+UlVuQ5GHI+mhaemON0AIoUlLlFPcK0ZrJsKd7enQnQ8ysw6G9z/s3249oPtNUv/Jcb3UreXJhDbswXRn7KAfNKJEomD0HTnOD338yXkbhGSt0Cqg73LdKPnprrLZCu3q2pnI6ZFhRzWvA7OBnCevfz5r/UDsAPLbQVKpK4NUSZRZupWHsI80kBfuCXk1BIAUa75CiL3D7w+Ii1CxMvSAkHq+QqzbWB6d5Dh5ftldXqdJ6Te768PNmQzXuHiYxsMEBKY=
  on:
    repo: nline/engagespark-topup
